In [2]:
from mxnet import nd

In [10]:
x = nd.arange(10)
x


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<NDArray 10 @cpu(0)>

In [11]:
x.shape

(10,)

In [12]:
x.size

10

In [14]:
 X = x.reshape((3, 3))
X


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)>

In [15]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [16]:
nd.ones((3, 5))


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<NDArray 3x5 @cpu(0)>

In [19]:
#均值为0，标准差为1，正态分布
nd.random.normal(0, 1, shape=(3, 4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [20]:
Y = nd.array([[3, 3, 2], [1, 3, 5], [2, 4, 5]])
Y


[[3. 3. 2.]
 [1. 3. 5.]
 [2. 4. 5.]]
<NDArray 3x3 @cpu(0)>

In [21]:
X + Y


[[ 3.  4.  4.]
 [ 4.  7. 10.]
 [ 8. 11. 13.]]
<NDArray 3x3 @cpu(0)>

In [22]:
X * Y


[[ 0.  3.  4.]
 [ 3. 12. 25.]
 [12. 28. 40.]]
<NDArray 3x3 @cpu(0)>

In [23]:
X / Y


[[0.         0.33333334 1.        ]
 [3.         1.3333334  1.        ]
 [3.         1.75       1.6       ]]
<NDArray 3x3 @cpu(0)>

In [24]:
Y.exp()


[[ 20.085537   20.085537    7.389056 ]
 [  2.7182817  20.085537  148.41316  ]
 [  7.389056   54.59815   148.41316  ]]
<NDArray 3x3 @cpu(0)>

In [26]:
nd.dot(X, Y.T)


[[ 7. 13. 14.]
 [31. 40. 47.]
 [55. 67. 80.]]
<NDArray 3x3 @cpu(0)>

In [28]:
nd.concat(X, Y, dim=0)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]
 [3. 3. 2.]
 [1. 3. 5.]
 [2. 4. 5.]]
<NDArray 6x3 @cpu(0)>

In [29]:
X == Y


[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
<NDArray 3x3 @cpu(0)>

In [30]:
X.sum()


[36.]
<NDArray 1 @cpu(0)>

In [34]:
X.norm().asscalar()

14.282856

In [36]:
Z = Y.zeros_like()
before = id(Z)
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True