In [1]:
from mxnet import autograd, nd

In [2]:
x = nd.arange(4).reshape((4, 1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [3]:
#申请存储梯度所需内存
x.attach_grad()

In [4]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [5]:
y.backward()

In [6]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [7]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [29]:
a = nd.random.normal(shape = 1)
a


[0.29956347]
<NDArray 1 @cpu(0)>

In [47]:
x = nd.arange(5).reshape((5,1))
x.attach_grad()
with autograd.record():
    y = x * x.T
y.backward()
x.grad


[[20.]
 [20.]
 [20.]
 [20.]
 [20.]]
<NDArray 5x1 @cpu(0)>

In [46]:
x * x.T


[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  4.  8. 12. 16.]]
<NDArray 5x5 @cpu(0)>